// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Next");

function handleClick(nextSlide, $$event) {
  if ($$event.defaultPrevented) {
    return 0;
  } else {
    $$event.preventDefault();
    return ReasonReact.Router[/* push */0]("/slide/" + String(nextSlide));
  }
}

function handleKeyUp(nextSlide, $$event) {
  console.log("Keyup");
  if ($$event.key === "ArrowRight") {
    console.log("Right Arrow" + String(nextSlide));
    return /* () */0;
  } else {
    return 0;
  }
}

function make(slide, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var partial_arg = slide + 1 | 0;
      var partial_arg$1 = slide + 1 | 0;
      return ReasonReact.createDomElement("a", {
                  href: "/slide/" + String(slide + 1 | 0),
                  onClick: (function (param) {
                      return handleClick(partial_arg, param);
                    }),
                  onKeyUp: (function (param) {
                      return handleKeyUp(partial_arg$1, param);
                    })
                }, /* array */["Next"]);
    });
  return newrecord;
}

exports.str = str;
exports.component = component;
exports.handleClick = handleClick;
exports.handleKeyUp = handleKeyUp;
exports.make = make;
/* component Not a pure module */
