// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function str(prim) {
  return prim;
}

var mySlideDeck = /* array */[
  React.createElement("div", {
        className: "slide"
      }, React.createElement("h1", undefined, "Ocaml"), React.createElement("h3", undefined, "Turns Out..."), React.createElement("h2", undefined, "The 'ml' is NOT for \"Mark Down\"")),
  React.createElement("div", {
        className: "slide"
      }, React.createElement("h1", undefined, "Reason"), React.createElement("h2", undefined, "A Slide Deck")),
  React.createElement("div", {
        className: "slide"
      }, React.createElement("h1", undefined, "Reason"), React.createElement("p", undefined, "Ocaml that gets complied into javascript.")),
  React.createElement("div", {
        className: "slide"
      }, React.createElement("p", undefined, "https://github.com/jachin/vormela"), React.createElement("p", undefined, "https://github.com/vramana/awesome-reasonml"))
];

exports.str = str;
exports.mySlideDeck = mySlideDeck;
/* mySlideDeck Not a pure module */
